analytics: {}
color:
  brandColors:
    - '#C0C8C0'
    - '#582820'
    - '#A86860'
    - '#904840'
    - '#000000'
  brandStrength: 0.636549
  lightness: 0.369086
  rhythmicContrast: 0.884559
  saturation: 0.355809
cta: {}
layout_spectrum: 0.910332
name: lluisconejeros
opengraph: {}
purpose: {}
typography_spectrum: 0.451851
