name: lluisconejeros
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28807
title: Quantum Bodywork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75003922-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccaeb0'
    - '#a9632f'
    - '#ad8e9d'
    - '#704b38'
    - '#e1d4e5'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
