name: lluisconejeros
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26302
title: Quantum Bodywork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75003922-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020126'
    - '#ffbcb7'
    - '#a63b32'
    - '#ff687d'
  brandStrength: 0.636549
  lightness: 0.369086
  saturation: 0.355809
  rhythmicContrast: 0.884559
purpose:
  - name: null
    item: null
    url: null
