name: lluisconejeros
favicon: null
layout_spectrum: 0.1454
typography_spectrum: 0.30541
title: Quantum Bodywork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75003922-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff4d6'
    - '#251808'
    - '#800000'
    - '#a09076'
    - '#f23b29'
  brandStrength: 0.636549
  lightness: 0.369086
  saturation: 0.355809
  rhythmicContrast: 0.884559
purpose:
  - name: null
    item: null
    url: null
